copy.out.fmea.path=C:/tmp/копия_{0}/{1}.docx
copy.out.pu.path=C:/tmp/копия_{0}/{1}.docx
copy.out.kp.path=C:/tmp/копия_{0}/{1}.docx
copy.out.wi.path=C:/tmp/копия_{0}/{1}.docx
copy.out.ri.path=C:/tmp/копия_{0}/{1}/{2}.docx
