#------- fmea --------------
inp.fmea.path=file:I:/KDiTD/IATF/templates/FMEA.docx
out.fmea.path=I:/KDiTD/IATF/{0}/FMEA{1}.docx
#------- pu --------------
inp.pu.path=file:I:/KDiTD/IATF/templates/PU.docx
out.pu.path=I:/KDiTD/IATF/{0}/\u041F\u0423{1}.docx
#------- kp --------------
inp.kp.path=file:I:/KDiTD/IATF/templates/KP.docx
out.kp.path=I:/KDiTD/IATF/{0}/\u041A\u041F{1}.docx
#------- wi --------------
inp.wi.path=file:I:/KDiTD/IATF/templates/WI.docx
out.wi.path=I:/KDiTD/IATF/{0}/\u0412\u0418{1}.docx
#------- ri --------------
inp.ri.path=file:I:/KDiTD/IATF/templates/RI.docx
out.ri.path=I:/KDiTD/IATF/{0}/{1}/{2}.docx
#------- sxpu --------------
inp.sxpu.path=file:I:/KDiTD/IATF/templates/SXPU.docx
out.sxpu.path=I:/KDiTD/IATF/{0}/\u0421\u0425\u041F\u0423{1}.docx
#------- tab01 --------------
inp.tab01.path=file:I:/KDiTD/IATF/templates/Table1.docx
out.tab01.path=I:/KDiTD/IATF/{0}/\u0422\u0430\u0431\u043B\u0438\u0446\u0430 01.docx